version: '3'
services:

  license:
    build: .
    container_name: "license"
    image: "license"
    environment:
      - CONFIG_FILE="/config/config.yml"
    ports:
      - 9200:9200
    volumes:
      - ${PWD}/config/config.yml:/config/config.yml
