version: '3'

services:
  db:
    container_name: "license-postgres"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: devpwd
      POSTGRES_USER: postgres
      POSTGRES_DB: license
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data 

  license:
    build: .
    container_name: "license"
    image: "license"
    environment:
      - CONFIG_FILE="/config/config.yml"
    ports:
      - 9200:9200
    volumes:
      - ${PWD}/config/config.yml:/config/config.yml
