ENV: dev
PORT: 9200
KEY: OLrqpXdOArsyinJTTnEQGw4efO1QsuvA
PUB_KEY: o/HlUXwbWIHqsMGmGVrruW72seuG5ws7PfO09LQEURI=
FILE_STORAGE: true
FILE_PATH: "license.txt"
MONGODB_STORAGE: false
MONGODB_CONN_STRING: ""
POSTGRES_STORAGE: false
POSTGRES_CONN_STRING: ""
