ENV_TYPE: dev
PORT: 9200
KEY: OLrqpXdOArsyinJTTnEQGw4efO1QsuvA
PUB_KEY: o/HlUXwbWIHqsMGmGVrruW72seuG5ws7PfO09LQEURI=
FILE_PATH: ""
MONGODB_CONN_STRING: ""
POSTGRES_ENABLE: true
POSTGRES_HOST: localhost 
POSTGRES_PORT: 5432
POSTGRES_USER: postgres
POSTGRES_PASSWORD: devpwd
POSTGRES_DB: license