ENV: dev
PORT: 9200
ENCRYPT_SEED: OLrqpXdOArsyinJTTnEQGw4efO1QsuvA
ENCRYPT_PUB_KEY: o/HlUXwbWIHqsMGmGVrruW72seuG5ws7PfO09LQEURI=
RE_ENCRYPT_SEED: CmsDWW1sjUgkLfEG2oBCtzm87z5i3S6F
RE_ENCRYPT_PUB_KEY: YVREDRVgCIDrOr+Hc7Fm0o3FxYKN9uiSVzXam0tDFJc=
FILE_PATH: license.txt
MONGODB_CONN_STRING: ""
POSTGRES_CONN_STRING: ""
